# Generated by Django 4.2 on 2024-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("file_name", models.TextField()),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
                ("user", models.IntegerField()),
            ],
        ),
    ]
